var frankreich_einwohner = 65.3;
var deutschland_einwohner = 83.2;
var italien_einwohner = 59.58;
var portugal_einwohner = 10.29;
var de = "Deutschland: ";
var fr = "Frankreich: ";
var it = "Italien: ";
var port = "Portugal: ";
var before = "Einwohner*innen in ";
var mio = " Mio";
console.log(before + de + deutschland_einwohner + mio);
console.log(before + fr + frankreich_einwohner + mio);
console.log(before + it + frankreich_einwohner + mio);
console.log(before + port + portugal_einwohner + mio);
var beforerel = "Relation zur Gesamtzahl der Einwohner*innen  in der EU ";
var eueinwohner = 447.01;
var hundert = 100;
var prozent = "%";
console.log(beforerel + de + deutschland_einwohner / eueinwohner * hundert + prozent);
console.log(beforerel + fr + frankreich_einwohner / eueinwohner * hundert + prozent);
console.log(beforerel + it + italien_einwohner / eueinwohner * hundert + prozent);
console.log(beforerel + port + portugal_einwohner / eueinwohner * hundert + prozent);
var beforerate = "Wachstumsrate seit 2008 ";
var de2008 = 82.0;
var fr2008 = 62.14;
var it2008 = 59.0;
var port2008 = 10.56;
console.log(beforerate + de + ((deutschland_einwohner - de2008) / de2008) * hundert + prozent);
console.log(beforerate + fr + ((frankreich_einwohner - fr2008) / fr2008) * hundert + prozent);
console.log(beforerate + it + ((italien_einwohner - it2008) / it2008) * hundert + prozent);
console.log(beforerate + port + ((portugal_einwohner - port2008) / port2008) * hundert + prozent);
var beforeges = "Wachstumsrate gesamt zwischen 2008 and 2021 ";
console.log(beforeges + de + (deutschland_einwohner - de2008) + mio);
console.log(beforeges + fr + (frankreich_einwohner - fr2008) + mio);
console.log(beforeges + it + (italien_einwohner - it2008) + mio);
console.log(beforeges + port + (portugal_einwohner - port2008) + mio);
//# sourceMappingURL=aufgabe6.js.map